### ISSUE TITLE
odom 데이터 angular 문제

### ISSUE THREAD

**Issue by KIM2C1** [J0ngWon/AMR_2023-2024#4]
#개요
odom 데이터의 angular 값이 크게 튐
##요구사항
목표치 1 rad/s
odom 1~2 rad/s 

버그 픽스 바람

**Comment by J0ngWon** [comment]
python 코드에서  blocking call 문제 40ms 마다 전송되는 데이터가 time.sleep(25) 로 인해 무시되어 생기는 문제로 현재 해결함
